In [1]:
import numpy as np

In [4]:
n = int(input('введите N '))
a = np.arange(n)
a = a[::-1]
print(a)

введите N 10
[9 8 7 6 5 4 3 2 1 0]


In [5]:
n = int(input('введите число'))

a = np.arange(n)
a = a[::-1]
mat = np.diag(a)
print(mat)

total_sum = 0
for i, line in enumerate(mat):
    total_sum += line[i]
print('сумма элементов диагонали = ', total_sum)

введите число10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
сумма элементов диагонали =  45


In [6]:
from numpy import linalg
a = np.array( [ [4, 2, 1], [1, 3, 0] , [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [7]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [8]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [10]:
best_match = {}
for i, line in enumerate(users_stats):
    best_match[cosine(line, next_user_stats)] = i
print('ID самого похожего пользователя = ', best_match[max(best_match.keys())])

ID самого похожего пользователя =  7
